### ISSUE TITLE
dialog disappears after rotation

### ISSUE THREAD

**Issue by anlalalu** [yeriomin/DumbphoneAssistant#19]
###### Reproduction Steps

1. tap 'SIM CARD'
2. tap 'delete' and a dialog appears
3. rotate the screen

###### Expected Result

The dialog still exists with no error log.

###### Actual Result

The dialog disappears with the stack trace:

E/WindowManager: android.view.WindowLeaked: Activity com.github.yeriomin.dumbphoneassistant.ManageContactsActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{529ee3c4 V.E..... R....... 0,0-729,242} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:286)
                                                    at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
                                                    at com.github.yeriomin.dumbphoneassistant.ManageContactsActivity$3.onClick(ManageContactsActivity.java:175)
                                                    at android.view.View.performClick(View.java:4438)
                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 0.5

Android Version = 4.4.4

**Comment by anlalalu** [comment]
Maybe solved with reference to this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

If you do consider this as a defect, please let me know. Thank you.
